"""Redwood City events via RSS feed.

redwoodcity.org is Akamai-blocked to all automated HTTP requests. This scraper
reads an RSS URL configured in config.yaml (e.g. generated by RSS.app or
FetchRSS pointed at the RWC events page, or a manually maintained feed).

Expected description format (flexible — all fields optional):
  "Location: Courthouse Square. Time: 06:00 PM. Event description text."

If the feed uses a different format, location falls back to "Redwood City"
and time falls back to midnight (normalizer will default duration to 1h).
"""
from __future__ import annotations

import logging
import re
from datetime import datetime, timedelta
from email.utils import parsedate_to_datetime
from xml.etree import ElementTree

import httpx

from ..event import Event
from .sanmateopl import _is_under_six

log = logging.getLogger(__name__)

TZ = "America/Los_Angeles"
UA = "Mozilla/5.0 (compatible; local-events-sync/1.0; +https://github.com/aviato-dev-agent/local-events-feed)"

_LOC_RE = re.compile(r"Location:\s*(.+?)(?:\.|$)", re.IGNORECASE)
_TIME_RE = re.compile(r"Time:\s*(\d{1,2}:\d{2}\s*[AP]M)", re.IGNORECASE)
_ADULT_TOKENS = ("adult", " 18+", " 21+", "seniors only")
_ADULT_ALLOW = ("family", "all ages", "kids", "children")
_CLOSURE_TOKENS = ("offices closed", "closed:", "holiday", "cancelled", "canceled")


def fetch(rss_url: str, city_tag: str = "RWC", lookahead_days: int = 90) -> list[Event]:
    events: list[Event] = []
    now = datetime.now()
    horizon = now + timedelta(days=lookahead_days)

    try:
        with httpx.Client(headers={"User-Agent": UA}, timeout=30, follow_redirects=True) as client:
            r = client.get(rss_url)
            r.raise_for_status()
            root = ElementTree.fromstring(r.content)
    except Exception as exc:
        log.warning("rwc_rss: fetch/parse failed for %s: %s", rss_url, exc)
        return events

    ns = {"atom": "http://www.w3.org/2005/Atom"}
    channel = root.find("channel")
    if channel is None:
        log.warning("rwc_rss: no <channel> element found")
        return events

    for item in channel.findall("item"):
        title = (item.findtext("title") or "").strip()
        if not title:
            continue

        pub_date = item.findtext("pubDate") or ""
        try:
            start = parsedate_to_datetime(pub_date).replace(tzinfo=None)
        except Exception:
            log.debug("rwc_rss: could not parse pubDate %r for %s", pub_date, title)
            continue

        if start < now - timedelta(hours=6) or start > horizon:
            continue

        raw_desc = item.findtext("description") or ""
        location, time_override, clean_desc = _parse_description(raw_desc)

        if time_override:
            try:
                t = datetime.strptime(time_override.strip().upper(), "%I:%M %p").time()
                start = start.replace(hour=t.hour, minute=t.minute, second=0, microsecond=0)
            except ValueError:
                pass

        link = (item.findtext("link") or "https://www.redwoodcity.org/residents/redwood-city-events/").strip()
        guid = (item.findtext("guid") or link).strip()

        if _is_closure(title):
            continue
        if _is_under_six(title, clean_desc, ""):
            continue
        if _is_adult_only(title, clean_desc):
            continue

        events.append(
            Event(
                source="rwc_rss",
                source_id=guid,
                city_tag=city_tag,
                title=title,
                start=start,
                end=None,
                location=location,
                description=clean_desc,
                ages="All ages",
                registration=None,
                url=link,
                tz=TZ,
            )
        )

    log.info("rwc_rss: %d events after filter", len(events))
    return events


def _parse_description(raw: str):
    """Extract location, time string, and clean description from raw description text."""
    location = "Redwood City"
    time_str = None

    loc_m = _LOC_RE.search(raw)
    if loc_m:
        location = loc_m.group(1).strip()

    time_m = _TIME_RE.search(raw)
    if time_m:
        time_str = time_m.group(1)

    clean = re.sub(r"Location:\s*.+?(?:\.|$)", "", raw, flags=re.IGNORECASE)
    clean = re.sub(r"Time:\s*\d{1,2}:\d{2}\s*[AP]M\.?\s*", "", clean, flags=re.IGNORECASE)
    clean = re.sub(r"\s+", " ", clean).strip().lstrip(". ")
    clean = clean[:800]

    return location, time_str, clean


def _is_closure(title: str) -> bool:
    return any(t in title.lower() for t in _CLOSURE_TOKENS)


def _is_adult_only(title: str, desc: str) -> bool:
    hay = f"{title} {desc}".lower()
    if any(t in hay for t in _ADULT_TOKENS):
        return not any(x in hay for x in _ADULT_ALLOW)
    return False
